export enum AuditEvent {
  USER_REGISTERED = 'USER_REGISTERED',

  LOGIN_SUCCESS = 'LOGIN_SUCCESS',

  LOGIN_FAILED = 'LOGIN_FAILED',

  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  PASSWORD_RESET = 'PASSWORD_RESET',

  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
}